### ISSUE TITLE
PROCESS BEING DEBUGGED HAS EXITED

### ISSUE THREAD

**Issue by adolson** [okamstudio/godot#1128]
PLEASE FIX THIS, REDUZ
/nag

**Comment by reduz** [comment]
THANKS

**Comment by not-surt** [comment]
If you mean not having to click away this dialog after every run then this has my support.

**Comment by Ace-Dragon** [comment]
Usually, this type of thing occurs when there is an iffy parent/child setup in the node tree or your script has something the parser can't recognize as an error, but is still invalid.

The problem, I don't think, is the fact that the dialogue is there, but the text needs to be replaced with more useful information (and maybe a highlight showing the invalid line of code or the invalid node parenting). I also don't know if it should be there when the game is exited via the engine's exit function (since the player would've put it there intentionally).

**Comment by adolson** [comment]
No, my node tree is perfectly valid. This occurs EVERY time you close your program, no matter what method you use to close it (other than pressing F8). It's a bug, and Juan asked me to open this so he doesn't forget to fix it.

**Comment by xodene** [comment]
I found where to get rid of it. It helps a lot not having to click this away after every run!

**Comment by adolson** [comment]
Yeah, I knew where to get rid of it, but Juan had said it was a bug with how the process exits (perhaps related to the zombie processes #727 ?), which is why my original PR (#913) to make it a preference wasn't merged, and why I opened this issue. But I see your change has been merged.. so I will close this anyhow.
