### ISSUE TITLE
3D TestCube appears white

### ISSUE THREAD

**Issue by UsernameIsAReservedWord** [okamstudio/godot#1185]
Hi,

It is caused by a recent change into the github source code.
The 3D TestCube appears white, and FixedMaterial are whiter too.

The change appeared between the 6th and the 10th of january.

Tested with win64 compiled versions.

**Comment by rraallvv** [comment]
Also there is something weird with those sides not facing the light source
![output](https://cloud.githubusercontent.com/assets/1840524/5791046/d48880fa-9e89-11e4-8594-378818544994.gif)

**Comment by shackra** [comment]
related to #1255 I guess

**Comment by rraallvv** [comment]
No, it seems an issue with some parameter in the cube material being set to a value out of range when it's created, the problem is that the material in the test cube can't be edited, only replaced by a new one.

**Comment by rraallvv** [comment]
I've found how to reproduce the issue with a custom material:
1. create a test cube
2. add a new fixed material to the cube
3. change the specular color to white (255,255,255)

... and also how to fix the issue in the default or custom material, the problem is that the specular exponent in an integer value, if it's changed to 40.0, the cube is rendered with a smooth transition from darkness to light

![output](https://cloud.githubusercontent.com/assets/1840524/5791599/dd1c1366-9eb2-11e4-97cc-099a88fc88cb.gif)

**Comment by UsernameIsAReservedWord** [comment]
( @rraallvv : what tool do you use to make these animated gif video ???? )

**Comment by rraallvv** [comment]
@UsernameIsAReservedWord [Here is how](http://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality#comment1025599_556031) with ffmpeg and imagemagic, on a mac both can be installed with [homebrew](http://brew.sh)

**Comment by UsernameIsAReservedWord** [comment]
( @rraallvv : thanks ! )

**Comment by monkz** [comment]
This issue affects me too. I experience it with godot-git-1.0._stable_544ce2a-1-x86_64.pkg.tar.xz on Arch Linux.

**Comment by reduz** [comment]
have just fixed it yesterday on github

**Comment by rraallvv** [comment]
This can be closed, it works fine now, thanks @reduz
