### ISSUE TITLE
[Bug] Closing Godot with a Texture in the tree is loosing properties

### ISSUE THREAD

**Issue by philiplb** [okamstudio/godot#1245]
See this project: http://www.philiplb.de/misc/BGTest.zip
The initial settings of the node "background" where:
Anchors:
- left: begin
- right: end
- top: begin
- bottom: end
Margins:
0, 0, 0, 0

I save the project and closed Godot. On reopening, all anchors are back to begin and the margins are set to 400, 300, 400, 300 leaving the size to 0 pixel.

Current workaround is to set it in _ready:

	var size = get_viewport_rect().size
	var background = get_node("background")
	background.set_custom_minimum_size(size)
	background.set_anchor(MARGIN_LEFT, ANCHOR_BEGIN)
	background.set_anchor(MARGIN_RIGHT, ANCHOR_END)
	background.set_anchor(MARGIN_TOP, ANCHOR_BEGIN)
	background.set_anchor(MARGIN_BOTTOM, ANCHOR_END)
	background.set_margin(MARGIN_LEFT, 0)
	background.set_margin(MARGIN_TOP, 0)
	background.set_margin(MARGIN_RIGHT, 0)
	background.set_margin(MARGIN_BOTTOM, 0)

**Comment by reduz** [comment]
Oh I see. A containers tutorial is really overdue..
This is because CenterContainer is a Container. The container system works by using the minimumsize of controls and ignoring the size you set to them, to later use an automatic layout.

What is happening here is that when TextureFrame is in "expand" mode, it no longer responds to it's minimum size (so it can be expanded). If you disable this property, it works but will not have the size you expect.

I suggest you do the following, since you are likely not needing this. Instead of using containers (or at-least CenterContainer), you can try instead using the "Center" anchor in controls to make sure the middle menu is kept centered.

**Comment by philiplb** [comment]
A, that makes sense, thanks. :)
