### ISSUE TITLE
Mouse button up event type

### ISSUE THREAD

**Issue by Sipaha** [okamstudio/godot#1350]
When mouse button down we get InputEvent with type MOUSE_BUTTON, but when mouse button up InputEvent type is MOUSE_MOTION. I think both of this events should be MOUSE_BUTTON with difference in member pressed.

**Comment by reduz** [comment]
you should get two MOUSE_BUTTON events, one with porperty pressed as true
and another with it as false

**Comment by Sipaha** [comment]
Oh, I apologize for my mistake. I created a label which shows type of event and, when mouse button released, it shows the MOUSE_MOTION. As it turned out when the button is released we have two events occur: MOUSE_BUTTON, MOUSE_MOTION and second overwrites the text in the label.

**Comment by blurymind** [comment]
@reduz that doesnt really solve it, because the on release event you propose gets repeatedly fired.

When you do
if InputEvent.MOUSE_BUTTON and event.is_pressed() and event.button_index == BUTTON_LEFT:
that triggers once

if you do 
if InputEvent.MOUSE_BUTTON and !event.is_pressed() and event.button_index == BUTTON_LEFT

godot fails to compile it

if you do 
if InputEvent.MOUSE_BUTTON and !event.is_pressed()

that gets repeatedly triggered while no button is pressed.

How do we make it fire a single time, when the left mouse button is released?
Without using any booleans

**Comment by vnen** [comment]
@blurymind If you're using it in `_input()`, it'll only be fired once for the released event. On `_process()`  there's no way around without using a boolean variable.

BTW `if InputEvent.MOUSE_BUTTON` does not make sense as code, I'm assuming you mean `if event.type == InputEvent.MOUSE_BUTTON`.
