### ISSUE TITLE
commenting and uncomenting (ctrl+k) a blank line with tabs in the script editor crashes godot

### ISSUE THREAD

**Issue by tuga3d** [okamstudio/godot#1484]
put some tabs on a blank line and comment and uncomment (ctrl+k) that line and godot crashes

this is the error i get on the terminal:

ERROR: get_selection_from_line: Condition ' !selection.active ' is true. returned: -1
   At: scene/gui/text_edit.cpp:2835.
ERROR: get_selection_from_line: Condition ' !selection.active ' is true. returned: -1
   At: scene/gui/text_edit.cpp:2835.
ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:128.

**Comment by theuserbl** [comment]
Verified. I think the problem is, that uncommenting the line, new Godot version also remove the tabs to have an empty line (don't know WHY Godot do this).
It all depends on the cursor position.
If your curser/caret position is _before_ the "#" and you press [Ctrl]+[K] it works ok.
If your cursor/carat position is _after_ the "#", then it crashed.
So I assume there is everywhere in a program something like
- save caret position in that line
- empty line
- go to old caret position at this line (where nothing is)

**Comment by reduz** [comment]
was this fixed eventually?

**Comment by tuga3d** [comment]
yes, is fixed.
