### ISSUE TITLE
Input action constantly pressed

### ISSUE THREAD

**Issue by FEDE0D** [okamstudio/godot#1673]
I'm making a game in android and I've noticed the input action get "stucked" when reloading the scene.

I'm using the "global.gd" technic to reload the scene.
```gdscript
func goto_scene(scene):
	# remove current scene from root and enqueue it for deletion
	# (when deleted, it will be removed)
	current_scene.queue_free()
	
	# load and add new scene to root
	var s = ResourceLoader.load(scene)
	current_scene = s.instance()
	get_tree().get_root().add_child(current_scene)
```

I use touchbuttons to control the character. On PC it works ok, but in Android if you reload the scene while holding down the touch for a button, the action is still pressed and the character walks constantly.

I don't know if this also happens in iOS or other touchscreen devices

**Comment by thecodethinker** [comment]
Could you also post the code where you check the input?

**Comment by FEDE0D** [comment]
This is the code for the movement
```gdscript
	if btnLeft.last() == 2:
		move(-player_speed, player_acceleration, delta)
		set_direction(DIR_LEFT)
		set_animation("running", .2, 1.2)
	elif btnRight.last() == 2:
		move(player_speed, player_acceleration, delta)
		set_direction(DIR_RIGHT)
		set_animation("running", .2, 1.2)
	else:
		move(0, player_acceleration, delta)
		set_animation("idle")
```

And I'm using [this implementation](http://pastebin.com/RavWKpjq) to get the state of the action

**Comment by thecodethinker** [comment]
Does it still read as being pressed after you tap it in the new scene?

**Comment by FEDE0D** [comment]
Yeap. The character keeps walking in the same direction. It doesn't respond to the actual tap in the new scene, it just keep walking (is_action_pressed) returns true.

**Comment by thecodethinker** [comment]
I'm guessing that whatever input reading is listening when the first scene dies never resets itself. Is the character the same ndoe between the scenes? Or does it get destroyed when the first scene does?

**Comment by reduz** [comment]
This is unfortunately not a bug, but what happens when scenes are changed during a callback or event.
You new scene is being added to the tree while the event is spreading, so it is also getting it.

This is my fault for proposing this scene changing method in the tutorials and demos originally, only later realized it was not a good idea.

To solve this problem, a new and safer method is proposed in both documentation and demos:

https://github.com/okamstudio/godot/wiki/tutorial_singletons#globalgd

and

https://github.com/okamstudio/godot/blob/ed5b93907720375e854ee67ae741145ab77e4d71/demos/misc/autoload/global.gd
