### ISSUE TITLE
set_name doesn't work if used with a name of queue_freed scene

### ISSUE THREAD

**Issue by kernelcrasher** [okamstudio/godot#2103]
I can select a node in my scene and delete it, but instancing and adding a new scene and changing its name to be the same as the deleted one's doesn't work. In other words, the engine doesn't permit using the name of the old node even though the node doesn't exist anymore.

```
func loadscene(scene):
	var nn = get_node("NamedNode")	
	nn.queue_free()
	var inst = scene.instance()
	add_child(inst)
	print("instance name before setting: ", inst.get_name())
	inst.set_name("NamedNode")
	print("instance name after setting: ", inst.get_name())
```
Produces:
```
instance name before setting: Node2D
instance name after setting: @Node2D5
```

**Comment by romulox-x** [comment]
I'm not sure I'd call this a bug, though the behavior can be a bit confusing.  queue_free doesn't actually remove the node from the scene yet.  It tells the engine to remove the node from the tree when it's safe to do so.  So it's still in the tree at this point, but flagged for removal.  You could try calling free() instead, but depending on your situation, it might not be safe to do this - for instance, if the node that's executing this function is within the scene being freed.  You could also rename the old scene to some temporary name, so that the name you want is available.

**Comment by kernelcrasher** [comment]
I confirm that renaming the node to be exchanged before calling queue_free() appears to work. This issue can be closed.
