### ISSUE TITLE
[BUG]The textfiled of script editor doesnt show all text by moving the silde.

### ISSUE THREAD

**Issue by zhagsenkk** [okamstudio/godot#2355]
Shown in picture.
![-1](https://cloud.githubusercontent.com/assets/10054853/9197189/dbe28166-4064-11e5-82ad-0df2169877f6.gif)

**Comment by AlexHolly** [comment]
I had the same bug, can you reproduce it?

**Comment by OvermindDL1** [comment]
I always can every time on all three computers that I have used it on.  It just send that whenever some lines get too long then it does not scroll all the way, but I can make it jump into view if I use the cursor to scroll over, but the bar stops and does not change.

**Comment by xodene** [comment]
I can also reproduce this bug.

**Comment by AlexHolly** [comment]
Now i can see it too.
I also had a similar bug where i couldn't scroll up (and down)? anymore. That i can't reproduce...

**Comment by zhagsenkk** [comment]
Maybe it is caused by TextEdit.Because TextEdit also has the similar bug.I try to understand the code logic,but its hard for me to debug.I have tried,but failed.

**Comment by Hodes** [comment]
I agree with this BUG. It's because of the box aside editor. I think the width of that box is being subtracted from editor's max scroll. To reproduce the bug with 100% chance, you should have a line of 
code that is larger than code editor's width. I tried to resize the script navigator aside editor, and then then the max scroll increased, so... 

![bugwitheditr](https://cloud.githubusercontent.com/assets/11355469/9409556/c6ca254c-47f1-11e5-8f97-471bcf3bf9c7.PNG)
