### ISSUE TITLE
crashed: duplication of animation

### ISSUE THREAD

**Issue by ret80** [okamstudio/godot#2418]
If you try to duplicate the animation occurs crashed

**Comment by reduz** [comment]
more context appreciated

**Comment by ret80** [comment]
example prj
https://yadi.sk/d/DguzCixxircKk

**Comment by ret80** [comment]
compile engine in VS2010

**Comment by reduz** [comment]
does not crash, works fine
![da](https://cloud.githubusercontent.com/assets/6265307/9735211/7d6782ec-560f-11e5-8b66-7906f139634d.png)

**Comment by vnen** [comment]
This actually happened to me once. If I tried to rename or duplicate the Editor just closed without explanation. Then I deleted the animation and created another and the problem never happened anymore.

So this might be a bug that occurs "randomly" and seems to be very rare.

**Comment by vnen** [comment]
Ok, I'm actually able to reproduce this. I compiled the editor myself at this commit: 2d570ac657d71f7967f6a520c672641f64b5272d

**Steps**:

1. Clone this demo I'm trying to make: https://github.com/vnen/godot-rpg2d
2. Checkout the commit vnen/godot-rpg2d@d1fa74ba3b2e722762b6deda60fb846204f64f17
3. Open the game in the editor.
4. Load the scene `entities/player.xscn`. The animation player will already be open and editing an animation.
5. Try to rename the open animation.
6. The editor closes with a Segmentation Fault.

**Comment by vnen** [comment]
I dug into the source code and found out the issue was introduced here: 1bad27e1f8460424fa4476fe65209aa250d43115.

The thing is that if you save a scene with the animation player opened, when you open the project again the player will be automatically opened again. However, when opened this way, the `set_undo_redo()` method is not called, so that field remains `null`. When you try to make a change, it tries to access this null `UndoRedo` object and then the editor crashes with a segfault.

**Comment by ret80** [comment]
the problem is still relevant. played 100%

https://dl.dropboxusercontent.com/u/80689824/ani_editor.png
