### ISSUE TITLE
streamplayer.play does now work for me

### ISSUE THREAD

**Issue by GrandFunkR** [okamstudio/godot#2492]
I have a StreamPlayer with an ogg file.

to play music I'm using:
get_node("/root/main/music").play()

about 2 months ago it worked.
Now executing this,  screen still freezed

**Comment by akien-mga** [comment]
StreamPlayer.play() now requires an argument since https://github.com/okamstudio/godot/commit/97413746173b4f872e8c72eba0e58d7092a93269#diff-f2891540866368691953e010a51009d8R139
It should be a float indicating the starting position in the track IIUC.

On the other hand there seems to be some issues, maybe @reduz can shed some light on this:
* The p_from_offset variable is passed to ```AudioStreamPlaybackMPC::play(float p_offset)``` IIUC, but apparently it's not used: https://github.com/okamstudio/godot/commit/97413746173b4f872e8c72eba0e58d7092a93269#diff-0d09ebecd3b3f73b38098b0d25526027R255
* The GDScript bound method seems to be defined with a default value of 0 for from_pos_sec, but it does not seem to make it an optional argument; if you don't provide a float argument to play(), the method errors out.

**Comment by akien-mga** [comment]
For the second bullet point above, the default value is actually only defined for the AudioStreamPlayback object. It should probably be defined too for StreamPlayer (https://github.com/okamstudio/godot/blob/97413746173b4f872e8c72eba0e58d7092a93269/scene/audio/stream_player.cpp#L328) and SpatialStreamPlayer (at least).

**Comment by akien-mga** [comment]
Thanks! What about my first bullet point above? Is the argument actually used, or not yet? If not, you should maybe open an issue or add a FIXME in the code to remember about it ;)

**Comment by okamstudio** [comment]
yes, the argument works, but only implemented on ogg vorbis

On Mon, Sep 21, 2015 at 3:51 AM, Rémi Verschelde <notifications@github.com>
wrote:

> Thanks! What about my first bullet point above? Is the argument actually
> used, or not yet? If not, you should maybe open an issue or add a FIXME in
> the code to remember about it ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2492#issuecomment-141892762>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
Ah indeed, thanks :)
