### ISSUE TITLE
Pausing scene

### ISSUE THREAD

**Issue by carlosmarti** [okamstudio/godot#2496]
Pausing the scene and then resuming the scene causes the pause button to not work again. 

The code that i am using is from the pause demo.
func _ready():
	# Initialization here
	connect("pressed",self,"on_pauseButton_pressed")

func on_pauseButton_pressed():
	get_parent().get_node("PopupMenu").set_exclusive(true)
	get_parent().get_node("PopupMenu").popup()
	get_tree().set_pause(true)

and this is the code to go back to the scene.

func _process(delta):
	if(get_node("levelselect").is_pressed()):
		get_tree().set_pause(false)
		get_node("/root/global").goto_scene("res://Assets/scenes/levelSelector.scn")
	if(get_node("resume").is_pressed()):
		get_tree().set_pause(false)
		hide()
	if(get_node("restart").is_pressed()):
		get_tree().set_pause(false)
		get_node("/root/global").goto_scene("res://Assets/levels/level_1.scn")

If i restart or go back to level select the button works fine. The problem is only when resuming the game.

**Comment by okamstudio** [comment]
Change the button pause mode

**Comment by carlosmarti** [comment]
Do you mean the function "set_toggle_mode()"?
I have set that to true and it still does the same thing.

**Comment by okamstudio** [comment]
no, check this..
https://github.com/okamstudio/godot/wiki/tutorial_pause

your button must be able to process during pause, you can change it as
described in the tutorial


On Sun, Sep 20, 2015 at 5:32 PM, Carlos Marti <notifications@github.com>
wrote:

> Do you mean the function "set_toggle_mode()"?
> I have set that to true and it still does the same thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2496#issuecomment-141831520>.
>



-- 

*OkamStudio*

**Comment by carlosmarti** [comment]
I see what you are saying. I changed the pause mode to process and it still does not fix the issue. Could it be that when the tree gets paused the button losses it's connection?

**Comment by eska014** [comment]
As explained in the [forum thread](http://www.godotengine.org/topics/12083?r=12112#message-12112), for BaseButton and its subclasses, `is_pressed()` is used to retrieve the toggle status for buttons with `is_toggle_mode() == true`, otherwise it will return `true` as long as it's pressed down. In this case, the button is being hidden while pressed down, so it returns `true` forever. Since the node is processing, it now unpauses every frame.
As a workaround, you could use signal(s) instead.
I suggest changing this issue or making a new issue to change buttons to no longer be in `is_pressed()` status when hidden.

**Comment by carlosmarti** [comment]
eska014 is correct. maybe buttons should no longer be in is_pressed().
