### ISSUE TITLE
Directory Object broken

### ISSUE THREAD

**Issue by ndee85** [okamstudio/godot#791]
Hey there..
I had a program which could create create directories and rename files.
With an older godot version everthing works fine. But with the current ones Directory is broken.
I still can create direcotories this way:
var dir = Directory.new()
dir.open("/")
dir.make_dir(dir_path)

But if I want to check if a dir exists or not the checks fail. I also cannot rename files anymore.

**Comment by UsernameIsAReservedWord** [comment]
same here with todays compiled win64 version.

`.dir_exists()` return always false, and `.file_exists()` say true when directory name is given.

**Comment by AnomalyAces** [comment]
Any idea when this will be addressed?

**Comment by reduz** [comment]
this is still broken I guess, will try to fix before 1.1

**Comment by NMNG** [comment]
Looking forward to this fix as well.  Fortunately read about it on the forums before I discovered it the hard way.  ;)

**Comment by Kermer** [comment]
1.1beta1 and still seems to be broken :(

**Comment by reduz** [comment]
ah thanks for the reminder

**Comment by Kermer** [comment]
Deleted last post since I was pretty sure I saw directories existance checking working somewhere, so:
`Directory.dir_exists()` doesn't work, but you can use `.file_exists()` instead (or even loop .get_next())
`.remove(), .copy(), .rename()` doesn't work as well ( probably no replacement for those :( ).

**Comment by kbdavidson** [comment]
Just spent a good part of the day rediscovering this issue on windows 7 64 bit using VS2010.

It seems an incomplete conversion from using GetFileAttributesA/W to GetFileAttributesExA/W was done.  The former would return the file attributes as the return value, for the Ex versions they must be retrieved from fileInfo.dwFileAttributes (the Ex versions return a bool success indicator so that was being treated as the attribute mask).

I did a quick fix of changing them to use the non-Ex versions.  Also saw uses of statements like 	p_file.replace("/","\\"); which I think are incorrect as it looks like String.replace does not modify the original string (thus it should be p_file = 	p_file.replace("/","\\");).  Not sure these are needed anyway, https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#paths documents that the Windows file API will change / to \ automatically.

NOTE - make_dir_recursive still does not work, it may be an issue up in dir_access.cpp.

Diffs for dir_access_windows.cpp:

@@ -237,7 +237,6 @@
 
 	p_dir=fix_path(p_dir);
 	
-	p_dir.replace("/","\\");
 
 	bool success;
 	int err;
@@ -308,11 +307,7 @@
 
 	p_file=fix_path(p_file);
 	
-	p_file.replace("/","\\");
-
-	WIN32_FILE_ATTRIBUTE_DATA    fileInfo;
-
 	if (unicode) {
 
 		DWORD fileAttr;
 
@@ -315,9 +310,9 @@
 	if (unicode) {
 
 		DWORD fileAttr;
 
-		fileAttr = GetFileAttributesExW(p_file.c_str(), GetFileExInfoStandard, &fileInfo);
-		if (0 == fileAttr)
+		fileAttr = GetFileAttributesW(p_file.c_str());
+		if (INVALID_FILE_ATTRIBUTES == fileAttr)
 			return false;
 
 		return !(fileAttr&FILE_ATTRIBUTE_DIRECTORY);
@@ -325,8 +320,8 @@
 	} else {
 		DWORD fileAttr;
 
-		fileAttr = GetFileAttributesExA(p_file.ascii().get_data(), GetFileExInfoStandard, &fileInfo);
-		if (0 == fileAttr)
+		fileAttr = GetFileAttributesA(p_file.ascii().get_data());
+		if (INVALID_FILE_ATTRIBUTES == fileAttr)
 			return false;
 
 		return !(fileAttr&FILE_ATTRIBUTE_DIRECTORY);
@@ -345,11 +340,7 @@
 
 	p_dir=fix_path(p_dir);
 
-	p_dir.replace("/","\\");
-
-	WIN32_FILE_ATTRIBUTE_DATA    fileInfo;
-
 	if (unicode) {
 
 		DWORD fileAttr;
 
@@ -352,9 +343,9 @@
 	if (unicode) {
 
 		DWORD fileAttr;
 
-		fileAttr = GetFileAttributesExW(p_dir.c_str(), GetFileExInfoStandard, &fileInfo);
-		if (0 == fileAttr)
+		fileAttr = GetFileAttributesW(p_dir.c_str());
+		if (INVALID_FILE_ATTRIBUTES == fileAttr)
 			return false;
 
 		return (fileAttr&FILE_ATTRIBUTE_DIRECTORY);
@@ -363,8 +354,8 @@
 #ifndef WINRT_ENABLED
 		DWORD fileAttr;
 
-		fileAttr = GetFileAttributesExA(p_dir.ascii().get_data(), GetFileExInfoStandard, &fileInfo);
-		if (0 == fileAttr)
+		fileAttr = GetFileAttributesA(p_dir.ascii().get_data());
+		if (INVALID_FILE_ATTRIBUTES == fileAttr)
 			return false;
 
 		return (fileAttr&FILE_ATTRIBUTE_DIRECTORY);
@@ -393,8 +384,8 @@
 	p_path=fix_path(p_path);
 	
 	printf("erasing %s\n",p_path.utf8().get_data());
-	WIN32_FILE_ATTRIBUTE_DATA    fileInfo;
-	DWORD fileAttr = GetFileAttributesExW(p_path.c_str(), GetFileExInfoStandard, &fileInfo);
+
+	DWORD fileAttr = GetFileAttributesW(p_path.c_str());
 	if (fileAttr == INVALID_FILE_ATTRIBUTES)
 		return FAILED;
 
----------------------------------------------
Test driver I created for testing this:

extends SceneTree

func _init():
	print ("_init ")
	
	var dir = Directory.new()
	dir.open("user://")
	assert dir.get_current_dir() == "user://"
	var tmpDir = str(OS.get_unix_time())
	assert dir.make_dir("user://" + tmpDir) == 0
	assert dir.dir_exists("user://" + tmpDir)
	assert dir.change_dir("user://" + tmpDir) == 0
	assert dir.get_current_dir() == "user://" + tmpDir
	assert dir.change_dir("user://") == 0
	assert dir.get_current_dir() == "user://"

# Broken - code is in dir_access.cpp	
#	assert dir.make_dir_recursive("user://" + tmpDir + "/" + tmpDir) == 0
#	assert dir.remove("user://" + tmpDir + "/" + tmpDir) == 0
	
	var newFile = File.new()
	var testFile = "user://" + tmpDir + "/testfile.txt"
	var renamedFile = "user://" + tmpDir + "/renamed.txt"
	newFile.open(testFile, File.WRITE)
	newFile.close()
	assert dir.file_exists(testFile)
	assert dir.rename(testFile, renamedFile) == 0
	assert dir.file_exists(renamedFile)
	
	assert dir.remove(renamedFile) == 0
	assert dir.remove("user://" + tmpDir) == 0

# Test for expected failures
	assert not dir.dir_exists("user://DOESNOTEXIST")
	assert not dir.file_exists("user://DOESNOTEXIST")
	
	print ("Main done - TESTS PASSED!")

	.quit()

**Comment by kbdavidson** [comment]
I just tried my test driver with 1.1rc2 and it fails on line 10, the dir.make_dir() line, with ERR_CANT_CREATE.  Manually creating the directory and commenting that line out, it fails on line 11 doing the dir_exists() check.  

I did not look closely at the changes made in 1.1rc2 but I know with the patches I have above this test driver runs all the way through with 1.0 stable + my patch.
